services:
  - type: web
    name: regime-dashboard
    env: python
    plan: free
    buildCommand: ""
    startCommand: streamlit run app.py --server.port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"
